openapi: 3.0.1
info:
  title: CountryISOCode
  description: API Definition of CountryISOCode
  version: 1.0.0
servers:
- url: http://localhost:8290/countrys
paths:
  /{isoCode}:
    get:
      parameters:
      - name: isoCode
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
