openapi: 3.0.1
info:
  title: CountryCodes
  description: API Definition of CountryCodes
  version: 1.0.0
servers:
- url: http://localhost:8290/countries
paths:
  /:
    get:
      responses:
        default:
          description: Default response
